### ISSUE TITLE
Deeper hierarchies

### ISSUE THREAD

**Issue by hmd78** [richard-peng-xia/HGCLIP#3]
Hi,
I'm interested in your work.
Can you explain how to have deeper hierarchies for datasets?
And do have any plan to release model weights?

**Comment by richard-peng-xia** [comment]
Hi @hmd78,

Thanks for your interest.

For your questions,
1. You can use some datasets with labels of deeper hierarchies (annotated) or leverage LLMs to automatically obtain deeper labels as described in Sec4.1 in the paper.
2. The release of model weights will be considered after the paper has been accepted.

Best,
Peng
